using System.Collections.Generic;
using UnityEngine;

public class ChunkManager {

    private Queue<Chunk> loadedChunks;
	private int seed;

	private const int MAX_CHUNKS = 8;

    public ChunkManager(int seed) {
		this.seed = seed;
        loadedChunks = new Queue<Chunk>();
		for (int i = 0; i < MAX_CHUNKS; i++)
			loadedChunks.Enqueue(GenerateChunk(i * Chunk.CHUNK_WIDTH, 5f, 1f));
	}

	public void Update(int playerX) {
		if(loadedChunks.Peek().getX() < playerX - 4 * Chunk.CHUNK_WIDTH) {
			loadedChunks.Dequeue();
			//shouldnt be playerX here
			loadedChunks.Enqueue(GenerateChunk(playerX, 5f, 1f));
		}
	}
	
	/*
		GenerateChunk()
		Parameters: Initial chance for a cell to be occupied, number of times to smooth, number of neighbors required for a birth or death.
		Returns: Newly created chunk containing the cells set as generated by cellular automata.
		Purpose: Create, initialize, and return the chunk so it can be rendered and populated later on.
	*/
	public Chunk GenerateChunk(int position, float frequency, float amplitude) {
		int[,] cells = new int[Chunk.CHUNK_WIDTH, Chunk.CHUNK_HEIGHT];

		InitializeCells(cells, position, frequency, amplitude);

		return new Chunk(cells);
	}

	/*
		InitializeCells
		Purpose: Sets all cells in map to an initial value of either 0 or 1 based on Perlin noise.
		Parameters: The 2D array of cells to initialize.
	*/
	private void InitializeCells(int[,] grid, int position, float frequency, float amplitude) {
		for (int x = 0; x < Chunk.CHUNK_WIDTH; x++) {
			float noise = Mathf.PerlinNoise(frequency * 0.01f * (position + x), seed);
			int height = (int)Mathf.Clamp(Mathf.Pow(noise, amplitude) * (float)Chunk.CHUNK_HEIGHT, 1f, (float)(Chunk.CHUNK_HEIGHT - 1));
			int y;
			for (y = 0; y < height; y++)
				grid[x, y] = 0;
			for (; y < Chunk.CHUNK_HEIGHT; y++)
				grid[x, y] = 1;
		}
	}

}
