using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GA_PU : PU_HUD_HANDLER
{
    /* The class GA_PU is a subclass of the PU_HUD_HANDLER class.  Inheriting all of the set variables and defined functions of the superclass.
     */
    private TimeOut goldenApple;
    public Text timer;
    /* The TimeOut goldenApple is another copy of the reference to the TimeOut script used for the powerups.  It allows the subclass GA_PU
     * to read the type variable and timeractive variable from the TimeOut script.  These variables indicate to the GA_PU class whether or not
     * it should act and if so for how long it should change the transparency of the powerup sprite.
     */

    private void Start()
    {
        goldenApple = FindObjectOfType<TimeOut>();
        powerUp.color = new Color(1f, 1f, 1f, 0.0f);
        timer.color = new Color(1.0f, 1.0f, 1.0f, 0.0f);

        Debug.Log(goldenApple.type);
    }
    /* At start the goldenApple object is set to the TimeOut object that is current generated by using the Unityengine function FindObjectOfType<>.  This sets the
     * variable goldenApple to the instance of the TimeOut class that is controlling the powerup on the screen.
     * The color of the golden apple power up sprite is also set to default color and full transparency.
     */


     private void Awake()
     {
         //powerUp = GameObject.GetComponent<SpriteRenderer>();
     }
     
   /* public override void powerUpTimer()
    {
        return;
    }*/

    /* The above functions, Awake and powerUpTimer, are not called by any class or subclass in the PU_HUD_HANDLER tree and are likely to be implemented in
     * future releases of the project.
     */

    // Update is called once per frame
    public override void Update()
    {
        if (goldenApple.type == 0)
        { 
           /* If the type of powerup on the screen is the golden apple then the rest of the function is enacted.  This type value is checked once per frame of the 
            * game.  The type must be compared to integers and there are currently 4 types of powerups that can be applied to type.  From 0 to 3.
            */
           // timer.text = " " + timeOut.timerActive;
            if (goldenApple.timerActive > 0.0f)
            {
                /* If the type of the power up is goldenApple and the timer active is greater than 0 then the goldenapple sprite becomes opaque.
                 * otherwise if the timeractive is at or below 0 then the sprite will fade to full transparency.
                 * The numbers compared to the timerActive variable must be floats as timerActive is a float value.
                 */
                float step = duration * Time.deltaTime;
                powerUp.color = new Color(1f, 1f, 1f, Mathf.Lerp(powerUp.color.a, maxAlpha, step));
                timer.color = new Color(0f, 0f, 0f, Mathf.Lerp(timer.color.a, maxAlpha, step));
                /* The timer.color changing functions are something that  may be implemented in a future release of the product but are not currently impacting
                 * the build in this version of the project.
                 */
            }
            else if (goldenApple.timerActive <= 0.0f)
            {
                float step = duration * Time.deltaTime;
                powerUp.color = new Color(1f, 1f, 1f, Mathf.Lerp(powerUp.color.a, minAlpha, step));
                timer.color = new Color(1f, 1f, 1f, Mathf.Lerp(timer.color.a, minAlpha, step));
            }
        }
    }
}
